services:
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile.dev 
    volumes:
      - .:/rails
    depends_on:
      - db
    environment:
      - DEV_DATABASE_URL=postgresql://postgres:password@db/pets_dev
      - TEST_DATABASE_URL=postgresql://postgres:password@db/pets_test
  db:
    image: postgres:16.2
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password

