ARG RUBY_VERSION=3.3.0
FROM registry.docker.com/library/ruby:$RUBY_VERSION-slim as base

# Install PostgreSQL dependencies
RUN apt-get update -qq 
RUN apt-get install --no-install-recommends -y postgresql postgresql-contrib libpq-dev

WORKDIR /rails

FROM base as build

# Install packages needed to build gems
RUN apt-get install --no-install-recommends -y build-essential git libvips pkg-config

# Install application gems
COPY rails/Gemfile ./rails/Gemfile
COPY rails/Gemfile.lock ./rails/Gemfile.lock
COPY modules ./modules
RUN ls ./
RUN cd ./rails && bundle install && \
    rm -rf ~/.bundle/ "${BUNDLE_PATH}"/ruby/*/cache "${BUNDLE_PATH}"/ruby/*/bundler/gems/*/.git && \
    bundle exec bootsnap precompile --gemfile
RUN cd ./modules/auth && bundle install
RUN cd ./modules/announcements && bundle install
RUN cd ./modules/announcements_search && bundle install
RUN cd ./modules/events_bus && bundle install

FROM base as workspace

WORKDIR /rails/rails

COPY --from=build /usr/local/bundle /usr/local/bundle

CMD ["rails", "server"]
