# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker compoase
      run:  docker compose build
    - name: Set up DB
      run:  |
        docker compose run web /bin/bash -c "cd /rails/rails; bundle exec rails db:create"
        docker compose run web /bin/bash -c "cd /rails/rails; bundle exec rails db:migrate RAILS_ENV=development"
        docker compose run web /bin/bash -c "cd /rails/rails; bundle exec rails db:migrate RAILS_ENV=test"
    - name: Run auth test
      run: docker compose run web /bin/bash -c "cd /rails/modules/auth; bundle exec rake test"
    - name: Run announcements test
      run: docker compose run web /bin/bash -c "cd /rails/modules/announcements; bundle exec rake test"
    - name: Run announcements search test
      run: docker compose run web /bin/bash -c "cd /rails/modules/announcements_search; bundle exec rake test"
    - name: Run events bus test
      run: docker compose run web /bin/bash -c "cd /rails/modules/events_bus; bundle exec rake test"
    - name: Run Rails tests
      run: docker compose run web /bin/bash -c "cd /rails/rails; bundle exec rails test"
    - name: Run Frontend type check
      run: docker compose run frontend npm run type-check
    - name: Run Frontend tests
      run: docker compose run frontend npm run test:unit run
    - name: Run Frontend linter
      run: docker compose run frontend npm run lint
